version: '3.7'

services:
  web:
    image: jusoch/juso-site
    command: gunicorn -w 4 -k uvicorn.workers.UvicornH11Worker juso.asgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/static/
      - media_volume:/home/app/web/media/
      - ./custom/:/home/app/web/custom/
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
      - cache
    restart: always
  cache:
    image: memcached:alpine
    restart: always
  smtp:
    image: namshi/smtp
    restart: always
    expose:
      - 25
  celery:
    image: jusoch/juso-site
    command: celery -A juso worker --loglevel WARN
    env_file:
      - ./.env.prod
  redis:
    image: redis
    expose:
      - 6379
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod
    restart: always
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/static/
      - media_volume:/home/app/web/media/
    networks:
      - web
      - default
    restart: always
    ports:
      - 8337:80
    expose:
      - 80
    depends_on:
      - web
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
    # - "traefik.basic.frontend.rule=Host:example.com"
      - "traefik.basic.port=80"
      - "traefik.basic.protocol=http"

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  web:
    external: true
