version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn -w 4 -k uvicorn.workers.UvicornH11Worker juso.asgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/static/
      - media_volume:/home/app/web/media/
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
      - cache
  cache:
    image: memcached:alpine
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/static/
      - media_volume:/home/app/web/media/
    networks:
      - web
      - default
    restart: always
    ports:
      - 8337:80
    expose:
      - 80
    depends_on:
      - web
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:dev.juso.ch,ag.dev.juso.ch"
      - "traefik.basic.port=80"
      - "traefik.basic.protocol=http"

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  web:
    external: true
